### ISSUE TITLE
Performance enhancement - Do not extract entries that will not be scanned or recursively extracted

### ISSUE THREAD

**Issue by justincranford** [whitesource/fs-agent#10]
Archive extraction in fs-agent explodes all entries to a temp folder. It then uses directory scanning with filters to eliminate most entries from scanning and recursive archive extraction. Why bother extracting entries that will subsequently ignored by directory scanning? Apply the same directory scan filters to the entry extraction, and performance becomes 10-20x faster.

Typical Java archive entries are 90-95% *.class files. There are others too like *.properties, *.xml, *.MF, and so on. None of them are supported by fs-agent for scanning or recursive extraction. It is a performance killer to extract those files to temp only to ignore them with the directory scan filters.

I wrote a test with Commons Compress and dir scanning. That handles all the same types as fs-agent except rpm and rar, so I added redline and unrar too. Same archive and compress support as fs-agent, and 10-20x faster extraction performance. Temp disk usage dropped by an order of magnitude, and memory and GC cycles also dropped significantly.

For example, the largest archive I regular scan is 1.2GB. tar containing 18 war files. Each war is a self-contained Sprint Boot application with embedded Tomcat and hundreds of jars. Extraction time went from 2 hours to less than 5 minutes. Also, I have a 4GB ram disk. Recursive extraction of everything uses 5GB of temp space, so I cannot run fs-agent with -Djava.io.tmpdir=/r. For smaller tar scans like 500MB, I can use -Djava.io.tmpdir=/r to mitigate the performance problems currently caused by extracting everything.

If you can apply the directory filters to the entry extraction, performance will improve. The added bonus of reduced temp usage would allow me to run fs-agent from my small ram disk too.

Thank you!

**Comment by eugenhoro** [comment]
Hi Justin, thank you for pointing this out and taking the time to add the details. This is included in the v1.8.9
