### ISSUE TITLE
Some tests are depending on files in C:\\Users\\ErezHuberman

### ISSUE THREAD

**Issue by rianwouters** [whitesource/fs-agent#14]
After cloning, tests are failing because files in C:\\Users\\ErezHuberman are referenced:

GradleLinesParserTest::parseLines
GradleDependencyResolverTest::resolveDependencies
GradleDependencyResolverTest::resolveDependencies2

**Comment by eRez-ws** [comment]
fixed in commit [56893bc](https://github.com/whitesource/fs-agent/commit/56893bcbf6c7c8b87582b403a51a773a485fd05c)
