### ISSUE TITLE
No error logging when parsing pom files fails

### ISSUE THREAD

**Issue by rianwouters** [whitesource/fs-agent#16]
If POM parsing throws an ParseException, an error message is printed: 
                logger.error("error parsing output : {} {}", e.getMessage());

However, if it throws an exception, only a debug message is printen:
                logger.debug("error parsing output : {} {}", e.getMessage(), mvnLines);

As the default loglevel is info, it obscures the error.
Took me a lot of time to find my parsing problem!

**Comment by raznitzan4** [comment]
Hi,

Thank you for opening this issue.
We add also a warn logging. You can see this here: f265dd441117132d2de8d1159e5ba33609387ff4

**Comment by rianwouters** [comment]
I think you should remove the debug error and add the nvmLines
