### ISSUE TITLE
Clearify status of this repository

### ISSUE THREAD

**Issue by asbachb** [whitesource/fs-agent#26]
Can you please clearify the status of this repository. 

Currently I'm quite unclear if this repository is abandoned or not. WhiteSource wiki states that

> The Unified Agent was previously named File System Agent (FSA).
https://whitesource.atlassian.net/wiki/spaces/WD/pages/33718339/Unified+Agent

But the release numbers differ from tags/releases on github.

It seems that development was moved to closed source. Could you please clearify if this project is still active and/or rename and/or put some information about the status in `README.MD`.

**Comment by mixellent** [comment]
@asbachb Thanks for reaching out! 
We have updated the README file with the relevant information.

This repository is still supported but not maintained anymore. Customers are advised to switch to the Unified Agent distribution.
