### ISSUE TITLE
gradle.preferredEnvironment has no effect. Agent uses "gradle" regardless of this setting.

### ISSUE THREAD

**Issue by SergeyMokhov** [whitesource/fs-agent#28]
As a result, users who set gradle.preferredEnvironment=wrapper will get error "Error getting results after running Gradle command"

Steps to reproduce:
- put gradle.preferredEnvironment=wrapper into whitesource.config
- try running the agent.

Expected result:
- Agent uses gradle wrapper instead of gradle

Actual result:
- Agent always uses gradle, ignoring the setting

The bug was introduced by this commit: https://github.com/whitesource/fs-agent/commit/d46d0419533d8c0ef4dae0408e5287deb0a6706e
The problem is in GradleCli and involves lines 39, 51 and 66.
I see 2 issues there:
- Overriding preferredEnvironment, which I believe is not meant to be changed and supposed to always represent something that user set in the config file. (Line 66 assumes that)
-  Incorrect use of ternary operator which sets preferredEnvironment to "gradle" if it was "wrapper" (lines 39 and 51)

**Comment by mixellent** [comment]
Thanks for reporting this @SergeyMokhov. Please note that we do not maintain this repository anymore.
Customers are advised to use the [Unified Agent](https://github.com/whitesource/unified-agent-distribution/tree/master/standAlone), which contains new features and improvements to the previous File System Agent.

For more information, please visit https://whitesource.atlassian.net/wiki/spaces/WD/pages/718405635/WhiteSource+Unified+Agent+Updates+January+2019.
