### ISSUE TITLE
ArchiveExtractor.extractArchive() should continue instead of return

### ISSUE THREAD

**Issue by justincranford** [whitesource/fs-agent#6]
I added an unrecognized filter to the "archiveIncludes" parameter in my config file (ex: **/*.so). That causes ArchiveExtractor to stop recursive scanning, which ends up skipping valid archives after the unrecognized archive file name.

The fix is a one line change. In version 1.8.5, change line 209 of ArchiveExtractor.java from "return" to "continue". I ran 1.8.5 from the source tag with and without the fix. Without the fix, recursion stops at the first error and missed many valid libraries after that point. With the fix, the error still shows but recursive scanning continues and includes the missed libraries.

If you could fix this for 1.8.6, it would be much appreciated.

**Comment by talarabov** [comment]
Hi Justin,

I am adding Support to the loop.

Thanks.

*Kind Regards,*
*Tal Arabov*
*Director of Customer Success*
[image:
https://docs.google.com/a/whitesourcesoftware.com/uc?id=0BwHnNFnDg6gdcElxOFhmbDhpVlE&export=download]

**Comment by tomshapira** [comment]
Resolved in commit 99c714b: this issue was fixed during resolution of issue #8, the ArchiveExtractor#handleArchiveFiles method was refactored, the archive process will continue even when encountering an unsopprted archive file type
